# 報單號碼常數
CUSTOM_DECLARATION_HEADER = "報單號碼"
PAGE_HEADER = CUSTOM_DECLARATION_HEADER
BEGINNING_DECLARATION_ID = CUSTOM_DECLARATION_HEADER
END_DECLARATION_ID = "納稅義務人統編"
# 納稅義務人統編
BEGINNING_TAX_ID_COLUMN = END_DECLARATION_ID
END_TAX_ID_P1 = "金額"
END_TAX_ID_P2 = "第 "
# 金額常數
BEGINNING_AMOUNT_COLUMN = "金額"
TABLE_COMPOSED_DATE = "製表日期:"
END_AMOUNT_COLUMN_P1 = TABLE_COMPOSED_DATE
RECORD_COUNT = "總筆數"
END_AMOUNT_COLUMN_P2 = RECORD_COUNT


PAGE_TAILER_1ST = TABLE_COMPOSED_DATE
FILE_TITLE = "彙總稅單稅單清單"
FILE_HEADER = FILE_TITLE
FILE_TAILER = RECORD_COUNT
CUSTOM_DECLARATION_TAILER = BEGINNING_TAX_ID_COLUMN
