# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PDF Project.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 750)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 750))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 750))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.dnd = QtWidgets.QFrame(self.centralwidget)
        self.dnd.setEnabled(True)
        self.dnd.setGeometry(QtCore.QRect(90, 120, 750, 450))
        self.dnd.setMinimumSize(QtCore.QSize(750, 450))
        self.dnd.setMaximumSize(QtCore.QSize(750, 450))
        self.dnd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dnd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dnd.setObjectName("dnd")
        self.formLayout = QtWidgets.QFormLayout(self.dnd)
        self.formLayout.setObjectName("formLayout")
        self.Selectioned = QtWidgets.QTableWidget(self.dnd)
        self.Selectioned.setObjectName("Selectioned")
        self.Selectioned.setColumnCount(3)
        self.Selectioned.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Selectioned.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Selectioned.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Selectioned.setHorizontalHeaderItem(2, item)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Selectioned)
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.dnd)
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.treeWidget_2.headerItem().setText(0, "1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.treeWidget_2)
        self.widget = QtWidgets.QWidget(self.dnd)
        self.widget.setAcceptDrops(True)
        self.widget.setObjectName("widget")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.widget)
        self.treeWidget = QtWidgets.QTreeWidget(self.dnd)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.treeWidget)
        self.Options = QtWidgets.QFrame(self.centralwidget)
        self.Options.setGeometry(QtCore.QRect(50, 580, 821, 151))
        self.Options.setMaximumSize(QtCore.QSize(1000, 1000))
        self.Options.setMouseTracking(True)
        self.Options.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Options.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Options.setObjectName("Options")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Options)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Merge = QtWidgets.QPushButton(self.Options)
        self.Merge.setMinimumSize(QtCore.QSize(0, 75))
        self.Merge.setObjectName("Merge")
        self.horizontalLayout.addWidget(self.Merge)
        self.Split = QtWidgets.QPushButton(self.Options)
        self.Split.setMinimumSize(QtCore.QSize(0, 75))
        self.Split.setObjectName("Split")
        self.horizontalLayout.addWidget(self.Split)
        self.Compress = QtWidgets.QPushButton(self.Options)
        self.Compress.setMinimumSize(QtCore.QSize(0, 75))
        self.Compress.setObjectName("Compress")
        self.horizontalLayout.addWidget(self.Compress)
        self.OCR = QtWidgets.QPushButton(self.Options)
        self.OCR.setMinimumSize(QtCore.QSize(0, 75))
        self.OCR.setObjectName("OCR")
        self.horizontalLayout.addWidget(self.OCR)
        self.Special = QtWidgets.QPushButton(self.Options)
        self.Special.setMinimumSize(QtCore.QSize(0, 75))
        self.Special.setObjectName("Special")
        self.horizontalLayout.addWidget(self.Special)
        self.Statistics = QtWidgets.QPushButton(self.Options)
        self.Statistics.setMinimumSize(QtCore.QSize(0, 75))
        self.Statistics.setObjectName("Statistics")
        self.horizontalLayout.addWidget(self.Statistics)
        self.Help = QtWidgets.QPushButton(self.Options)
        self.Help.setMinimumSize(QtCore.QSize(0, 75))
        self.Help.setObjectName("Help")
        self.horizontalLayout.addWidget(self.Help)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 30, 851, 71))
        self.textBrowser.setAutoFillBackground(True)
        self.textBrowser.setObjectName("textBrowser")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(False)
        self.frame.setGeometry(QtCore.QRect(450, 410, 491, 301))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(20, 60, 401, 71))
        self.textEdit.setAcceptDrops(False)
        self.textEdit.setObjectName("textEdit")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(10, 270, 441, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(160, 180, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.Helpwidget = QtWidgets.QTabWidget(self.centralwidget)
        self.Helpwidget.setEnabled(True)
        self.Helpwidget.setGeometry(QtCore.QRect(470, 70, 461, 331))
        self.Helpwidget.setAutoFillBackground(True)
        self.Helpwidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.Helpwidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Helpwidget.setMovable(False)
        self.Helpwidget.setObjectName("Helpwidget")
        self.merge = QtWidgets.QWidget()
        self.merge.setObjectName("merge")
        self.information = QtWidgets.QPlainTextEdit(self.merge)
        self.information.setGeometry(QtCore.QRect(21, 21, 351, 192))
        self.information.setAcceptDrops(False)
        self.information.setObjectName("information")
        self.Exit = QtWidgets.QPushButton(self.merge)
        self.Exit.setGeometry(QtCore.QRect(160, 220, 75, 25))
        self.Exit.setObjectName("Exit")
        self.Helpwidget.addTab(self.merge, "")
        self.seperate = QtWidgets.QWidget()
        self.seperate.setObjectName("seperate")
        self.Exit_2 = QtWidgets.QPushButton(self.seperate)
        self.Exit_2.setGeometry(QtCore.QRect(160, 220, 75, 25))
        self.Exit_2.setObjectName("Exit_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.seperate)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 20, 351, 181))
        self.textEdit_2.setAcceptDrops(False)
        self.textEdit_2.setObjectName("textEdit_2")
        self.Helpwidget.addTab(self.seperate, "")
        self.compress = QtWidgets.QWidget()
        self.compress.setObjectName("compress")
        self.Exit_3 = QtWidgets.QPushButton(self.compress)
        self.Exit_3.setGeometry(QtCore.QRect(160, 220, 75, 25))
        self.Exit_3.setObjectName("Exit_3")
        self.textEdit_3 = QtWidgets.QTextEdit(self.compress)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 20, 351, 181))
        self.textEdit_3.setAcceptDrops(False)
        self.textEdit_3.setObjectName("textEdit_3")
        self.Helpwidget.addTab(self.compress, "")
        self.searchable = QtWidgets.QWidget()
        self.searchable.setObjectName("searchable")
        self.Exit_4 = QtWidgets.QPushButton(self.searchable)
        self.Exit_4.setGeometry(QtCore.QRect(160, 220, 75, 25))
        self.Exit_4.setObjectName("Exit_4")
        self.textEdit_4 = QtWidgets.QTextEdit(self.searchable)
        self.textEdit_4.setGeometry(QtCore.QRect(20, 20, 351, 181))
        self.textEdit_4.setAcceptDrops(False)
        self.textEdit_4.setObjectName("textEdit_4")
        self.Helpwidget.addTab(self.searchable, "")
        self.special = QtWidgets.QWidget()
        self.special.setObjectName("special")
        self.Exit_5 = QtWidgets.QPushButton(self.special)
        self.Exit_5.setGeometry(QtCore.QRect(160, 220, 75, 25))
        self.Exit_5.setObjectName("Exit_5")
        self.textEdit_5 = QtWidgets.QTextEdit(self.special)
        self.textEdit_5.setGeometry(QtCore.QRect(20, 20, 351, 181))
        self.textEdit_5.setAcceptDrops(False)
        self.textEdit_5.setObjectName("textEdit_5")
        self.Helpwidget.addTab(self.special, "")
        self.statistics = QtWidgets.QWidget()
        self.statistics.setObjectName("statistics")
        self.Exit_6 = QtWidgets.QPushButton(self.statistics)
        self.Exit_6.setGeometry(QtCore.QRect(160, 220, 75, 25))
        self.Exit_6.setObjectName("Exit_6")
        self.textEdit_6 = QtWidgets.QTextEdit(self.statistics)
        self.textEdit_6.setGeometry(QtCore.QRect(20, 20, 351, 181))
        self.textEdit_6.setAcceptDrops(False)
        self.textEdit_6.setObjectName("textEdit_6")
        self.Helpwidget.addTab(self.statistics, "")
        self.confirm = QtWidgets.QFrame(self.centralwidget)
        self.confirm.setGeometry(QtCore.QRect(10, 230, 381, 281))
        self.confirm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.confirm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.confirm.setObjectName("confirm")
        self.replace = QtWidgets.QDialogButtonBox(self.confirm)
        self.replace.setGeometry(QtCore.QRect(90, 110, 161, 32))
        self.replace.setOrientation(QtCore.Qt.Horizontal)
        self.replace.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.replace.setObjectName("replace")
        self.Info = QtWidgets.QTextEdit(self.confirm)
        self.Info.setGeometry(QtCore.QRect(10, 30, 331, 131))
        self.Info.setAcceptDrops(False)
        self.Info.setAutoFillBackground(True)
        self.Info.setObjectName("Info")
        self.confirm_2 = QtWidgets.QDialogButtonBox(self.confirm)
        self.confirm_2.setGeometry(QtCore.QRect(20, 230, 341, 32))
        self.confirm_2.setOrientation(QtCore.Qt.Horizontal)
        self.confirm_2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.confirm_2.setObjectName("confirm_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Helpwidget.setCurrentIndex(5)
        self.Help.clicked.connect(self.Helpwidget.show)
        self.Merge.clicked.connect(self.confirm.update)
        self.Merge.released.connect(self.confirm.show)
        self.Split.clicked.connect(self.confirm.update)
        self.Compress.clicked.connect(self.confirm.update)
        self.OCR.clicked.connect(self.confirm.update)
        self.Special.clicked.connect(self.confirm.update)
        self.Statistics.clicked.connect(self.confirm.update)
        self.Split.released.connect(self.confirm.show)
        self.Compress.released.connect(self.confirm.show)
        self.OCR.released.connect(self.confirm.show)
        self.Special.released.connect(self.confirm.show)
        self.Statistics.released.connect(self.confirm.show)
        self.confirm_2.accepted.connect(self.confirm.close)
        self.confirm_2.accepted.connect(self.frame.show)
        self.confirm_2.accepted.connect(self.Options.hide)
        self.Exit.clicked.connect(self.Helpwidget.close)
        self.Exit_2.clicked.connect(self.Helpwidget.close)
        self.Exit_3.clicked.connect(self.Helpwidget.close)
        self.Exit_4.clicked.connect(self.Helpwidget.close)
        self.Exit_5.clicked.connect(self.Helpwidget.close)
        self.Exit_6.clicked.connect(self.Helpwidget.close)
        self.confirm_2.accepted.connect(self.dnd.hide)
        self.pushButton.clicked.connect(self.textEdit.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.textBrowser, self.Merge)
        MainWindow.setTabOrder(self.Merge, self.Split)
        MainWindow.setTabOrder(self.Split, self.Compress)
        MainWindow.setTabOrder(self.Compress, self.OCR)
        MainWindow.setTabOrder(self.OCR, self.Special)
        MainWindow.setTabOrder(self.Special, self.Statistics)
        MainWindow.setTabOrder(self.Statistics, self.Help)
        MainWindow.setTabOrder(self.Help, self.treeWidget)
        MainWindow.setTabOrder(self.treeWidget, self.Selectioned)
        MainWindow.setTabOrder(self.Selectioned, self.treeWidget_2)
        MainWindow.setTabOrder(self.treeWidget_2, self.Helpwidget)
        MainWindow.setTabOrder(self.Helpwidget, self.information)
        MainWindow.setTabOrder(self.information, self.Exit)
        MainWindow.setTabOrder(self.Exit, self.textEdit_2)
        MainWindow.setTabOrder(self.textEdit_2, self.Exit_2)
        MainWindow.setTabOrder(self.Exit_2, self.textEdit_3)
        MainWindow.setTabOrder(self.textEdit_3, self.Exit_3)
        MainWindow.setTabOrder(self.Exit_3, self.textEdit_4)
        MainWindow.setTabOrder(self.textEdit_4, self.Exit_4)
        MainWindow.setTabOrder(self.Exit_4, self.textEdit_5)
        MainWindow.setTabOrder(self.textEdit_5, self.Exit_5)
        MainWindow.setTabOrder(self.Exit_5, self.textEdit_6)
        MainWindow.setTabOrder(self.textEdit_6, self.Exit_6)
        MainWindow.setTabOrder(self.Exit_6, self.Info)
        MainWindow.setTabOrder(self.Info, self.textEdit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.centralwidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>The main landing and selection page</p></body></html>"))
        item = self.Selectioned.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Filename"))
        item = self.Selectioned.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Group"))
        item = self.Selectioned.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Size"))
        self.Merge.setText(_translate("MainWindow", "Merge"))
        self.Split.setText(_translate("MainWindow", "Seperate"))
        self.Compress.setText(_translate("MainWindow", "Compress"))
        self.OCR.setText(_translate("MainWindow", "Searchable"))
        self.Special.setText(_translate("MainWindow", "Special"))
        self.Statistics.setText(_translate("MainWindow", "Statistics"))
        self.Help.setText(_translate("MainWindow", "Help"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Welcome to my PDF program</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you have any questions press the help button</p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Put the information here when it starts</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "ELAPSE TIME"))
        self.information.setPlainText(_translate("MainWindow", "The merging function merges pdf based on the order they are presented. Be careful because more than 1 and it will do based on how it wants and you cant do shit"))
        self.Exit.setText(_translate("MainWindow", "Exit"))
        self.Helpwidget.setTabText(self.Helpwidget.indexOf(self.merge), _translate("MainWindow", "Merge"))
        self.Exit_2.setText(_translate("MainWindow", "Exit"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter Information Here</p></body></html>"))
        self.Helpwidget.setTabText(self.Helpwidget.indexOf(self.seperate), _translate("MainWindow", "Seperate"))
        self.Exit_3.setText(_translate("MainWindow", "Exit"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter Information Here</p></body></html>"))
        self.Helpwidget.setTabText(self.Helpwidget.indexOf(self.compress), _translate("MainWindow", "Compress"))
        self.Exit_4.setText(_translate("MainWindow", "Exit"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter Information Here</p></body></html>"))
        self.Helpwidget.setTabText(self.Helpwidget.indexOf(self.searchable), _translate("MainWindow", "Searchable"))
        self.Exit_5.setText(_translate("MainWindow", "Exit"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter Information Here</p></body></html>"))
        self.Helpwidget.setTabText(self.Helpwidget.indexOf(self.special), _translate("MainWindow", "Special"))
        self.Exit_6.setText(_translate("MainWindow", "Exit"))
        self.textEdit_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter Information Here</p></body></html>"))
        self.Helpwidget.setTabText(self.Helpwidget.indexOf(self.statistics), _translate("MainWindow", "Statistics"))
        self.Info.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You have selected &lt;Insert the part that is passed in&gt;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&lt;Give details on what it is going to do&gt;</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Do you want to replace existing files</p></body></html>"))
